#!/usr/bin/env bash

# Check if NetworkManager is running
if ! pgrep -x "NetworkManager" > /dev/null; then
    rofi -dmenu -p "Root Password" | sudo -S systemctl start NetworkManager
fi

# Notify about scanning networks
notify-send "Wi-Fi" "Getting list of available Wi-Fi networks..."

# Get the list of available Wi-Fi networks (SSID and security only)
wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed '/^--/d')

# Determine Wi-Fi toggle state
wifi_state=$(nmcli -fields WIFI g)
if [[ "$wifi_state" == *"enabled"* ]]; then
    toggle="Disable Wi-Fi"
else
    toggle="Enable Wi-Fi"
fi

# Show menu
chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | rofi -dmenu -i -selected-row 1 -p "SSID")
chosen_id=$(echo "$chosen_network" | awk '{print $2}' | xargs)

# Exit if no selection
if [[ -z "$chosen_network" ]]; then
    exit
elif [[ "$chosen_network" == "Enable Wi-Fi" ]]; then
    nmcli radio wifi on
elif [[ "$chosen_network" == "Disable Wi-Fi" ]]; then
    nmcli radio wifi off
else
    # Connection handling
    success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
    saved_connections=$(nmcli -g NAME connection)
    
    if echo "$saved_connections" | grep -qw "$chosen_id"; then
        nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "Wi-Fi Connected" "$success_message"
    else
        wifi_password=$(rofi -dmenu -p "Password")
        nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Wi-Fi Connected" "$success_message"
    fi
fi
